version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: sectorsoft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    build: .
    command: python manage.py migrate
    depends_on:
      - db
    environment:
      POSTGRES_DB: sectorsoft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/app
    # No ports - not exposed

  web:
    build: .
    command: gunicorn sector_soft_task.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
      - migrate
    environment:
      POSTGRES_DB: sectorsoft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_ALLOWED_HOSTS: "*"
      SECRET_KEY: secret_key
      TELEGRAM_BOT_TOKEN: token
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  bot:
    build: .
    command: python manage.py runbot
    depends_on:
      - db
      - migrate
    environment:
      POSTGRES_DB: sectorsoft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: secret_key
      TELEGRAM_BOT_TOKEN: token
    volumes:
      - .:/app

volumes:
  pgdata: